### PR TITLE
Allow PHP 7.0.

### LINKED ISSUE #69: Release 1.1.2 disallow PHP 7
Hi,
why with release [1.1.2](https://github.com/zfcampus/zf-content-negotiation/compare/1.1.1...1.1.2) in `composer.json` php requirement was changed from `>=5.5` to `^5.5`?
Now is not possible to use it on PHP7.

https://github.com/zfcampus/zf-content-negotiation/commit/9d0bcea51cfcaffad059ed4fa92dae64f1283702#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R29

### PR DESCRIPTION
**Pull request by MichaelGooden**
Fixes #69.

Also removes PHP 7 from the Travis `allow_failures` config.

### CODE REVIEW

**Comment by TomHAnderson** [comment]
@MichaelGooden I think you should add removal of the allow_failures to this PR.

**Comment by MichaelGooden** [comment]
@TomHAnderson Done.

I suggest removing the `--ignore-platform-reqs` from https://github.com/zfcampus/zf-content-negotiation/blob/master/.travis.yml#L33 to prevent a regression in future.

**Comment by snapshotpl** [comment]
@weierophinney can you take a look?

**Comment by chateaux** [comment]
@weierophinney Patch looks solid - please merge!

**Comment by MichaelGooden** [comment]
@TomHAnderson Any reason you cannot merge this for us? I understand @weierophinney is busy with ZF3 stuff, but his bug is pretty nasty for anyone using PHP 7.0.

**Comment by TomHAnderson** [comment]
Sorry @MichaelGooden I don't have enough access to all the repositories.

ping @ezimuel

**Comment by Michal-sk** [comment]
darn...

**Comment by MichaelGooden** [comment]
Now that ZF3 is finished, ping @weierophinney :)

**Comment by weierophinney** [comment]
I'm also going to remove support for PHP 5.5 when merging, and target v1.2 for the release.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.2.0.

**Comment by MichaelGooden** [comment]
@weierophinney Would a hotfix for 1.1.x just adding support back for PHP 7 not be in order?

**Pull request closed without merging**
